/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package pietSmietQuizShowSolver

fun main() {
    Main(floatArrayOf(-10F, 15F, 15F, 5F, 13F), -5F).solution()
}
// TODO add cli interface
// TODO add testing