/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package arithmeticOperatorSolver

fun main() {
    Solver(floatArrayOf(-10F, 15F, 15F, 5F, 13F), -5F)
}
// TODO add cli interface